modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/RicoBrase/ChatCalculator/issues"
[[mods]]
modId="chatcalculator"
version="${file.jarVersion}"
displayName="ChatCalculator"
displayURL="https://github.com/RicoBrase/ChatCalculator"
logoFile="logo.png"
credits="Dennis0712 for the mod idea."
authors="RicoBrassers"
description='''
Calculate from ingame chat.
'''
[[dependencies.chatcalculator]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.chatcalculator]]
modId="minecraft"
mandatory=true
versionRange="[1.20,2)"
ordering="NONE"
side="BOTH"
